# Generated by Django 4.0.3 on 2022-05-09 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(null=True)),
                ('specialization', models.CharField(choices=[('Doctor', 'Doctor'), ('Sevika', 'Sevika'), ('NGO', 'NGA')], max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('qualification', models.CharField(choices=[('No Formal education', 'No Formal education'), ('Primary Education', 'Primary Educations'), ('Secondary Education', 'Secondary Education'), ('Post Graduation diploma', 'Post Graduation Diploma'), ('Vocational Qualification', 'Vocational Qualification'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree'), ('Doctorate or Higher', 'Doctorate or Higher')], max_length=30)),
                ('dob', models.DateField()),
                ('blood_grp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('country', models.CharField(default='India', max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
