# Generated by Django 4.0.3 on 2022-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='symptoms',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
