# Generated by Django 4.0.3 on 2022-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_arm_customuser_bp_dia_customuser_bp_sys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='symptoms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
