# Generated by Django 4.0.3 on 2022-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser_disease_alter_customuser_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
