# Generated by Django 4.0.3 on 2022-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Screener', 'Screener'), ('Sevika', 'Sevika'), ('Ngo', 'Ngo'), ('Pharmacy', 'Pharmacy')], max_length=30, null=True),
        ),
    ]
