# Generated by Django 4.0.3 on 2022-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customuser_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Issue_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Issue_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='issue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
