# Generated by Django 4.0.3 on 2022-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='adhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
