# Generated by Django 4.0.3 on 2022-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_survey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='adhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
