# Generated by Django 4.1.7 on 2023-04-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_survey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user',
            new_name='user_id',
        ),
    ]
