# Generated by Django 4.1.7 on 2023-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_survey_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user_id',
            new_name='user',
        ),
    ]
