# Generated by Django 4.1.7 on 2023-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_user_id_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='upload',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
