# Generated by Django 4.1.7 on 2023-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_survey_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='upload',
        ),
        migrations.AddField(
            model_name='customuser',
            name='upload',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
